# Generated by Django 4.2.4 on 2023-08-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gametype',
            old_name='name',
            new_name='label',
        ),
    ]
